apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ArgocdDenyAppInDefaultProject
metadata:
  name: argocddenyappindefaultproject
spec:
  match:
    kinds:
    - apiGroups:
      - argoproj.io
      kinds:
      - Application
