apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ArgocdDenyAppInArbitrarilyProjects
metadata:
  name: argocddenyappinarbitrarilyprojects
spec:
  match:
    kinds:
    - apiGroups:
      - argoproj.io
      kinds:
      - Application
  parameters:
    projects: ["deny", "default"]
